from fastapi.openapi.utils import get_openapi


def custom_openapi_factory(app):
    """This method solves a known issue that was reported on FastAPI#1442 in
    which the schema for file upload routes were auto-generated with no
    customization options.

    Args:
       app: The FastAPI application to modify.
    """

    def custom_openapi():
        if app.openapi_schema:
            return app.openapi_schema

        openapi_schema = get_openapi(
            title="Custom title",
            version="2.5.0",
            description="This is a custom OpenAPI schema",
            routes=app.routes,
        )
        # Move autogenerated Body_ schemas, see https://github.com/tiangolo/fastapi/issues/1442
        for path in openapi_schema["paths"].values():
            for method_data in path.values():
                if "requestBody" in method_data:
                    for content_type, content in method_data["requestBody"][
                        "content"
                    ].items():
                        if content_type == "multipart/form-data":
                            schema_name = content["schema"]["$ref"].lstrip(
                                "#/components/schemas/"
                            )
                            schema_data = openapi_schema["components"]["schemas"].pop(
                                schema_name
                            )
                            content["schema"] = schema_data
        app.openapi_schema = openapi_schema

        return app.openapi_schema

    return custom_openapi
